### ISSUE TITLE
Attribute value extraction

### ISSUE THREAD

**Issue by jasminejaksic** [istio/proxy#165]
Extract attributes such as source.name.

**Comment by ZackButcher** [comment]
Istio's canonical attributes are listed [here](https://github.com/istio/istio.github.io/blob/master/docs/reference/attributes.md). There's a few more that the proxy can provide but is not today:

* request.method - the HTTP method of the request, e.g. POST, PUT, GET, etc.
* request.referer - HTTP `Referer` header
* request.scheme - this can be hard coded to HTTP since attributes are produced in an HTTP filter, I think
* request.user-agent - HTTP `User-Agent` header
* request.id - "This should be a guid or a psuedo-guid with a low probability of collision in a temporal window measured in days or weeks."
* source.ip - "The IP address of the client that sent the request."
* source.port 
* origin.ip - "The IP address of the originating application."
* origin.port
* target.ip - "	The IP address the request was sent to."
* target.port

@smawson we need some clarification on the `source`/`origin` attributes: AFAIK `source.{ip, port}` should be extracted from TCP connection and `origin.{ip, port}` should be extracted from the `x-forward-for` headers. Is that correct?

We rely on the manager to populate `target.ip` and `target.port` in config it pushes to proxy, @kyessenov can you confirm?

**Comment by smawson** [comment]
We could ignore origin.ip and origin.port for now if we want to, that's meant to be passed from the ingress proxy. So proxy-specific how it wants to do that, x-forward-for would be reasonable if it is supported by envoy easily.

source.ip/port are just from the connection, yeah.

**Comment by ZackButcher** [comment]
Per a chat with @smawson we're going to punt on the `origin` attributes till we nail down ingress, but we should still try to get in the others for alpha. @qiwzhang is there anything that you know of in Envoy that'd make getting any of these hard? If not I might try my hand at adding them.

**Comment by qiwzhang** [comment]
Hi @ZackButcher It will be great if you can help.  I am kind of short handed.   

it will be straight forward to get these request.* attributes.
source.ip we could get it from XFF, but not sure about source.port

It will be hard to get target.ip and port in Envoy.  @lizan or @kyessenov  may know how

**Comment by ZackButcher** [comment]
So adding all of the request attributes is easy and I'll be sending out a PR implementing it soon. However, source.ip/port are harder because the mixerclient does not yet support IP_ADDRESS attributes. I'm eyeing up what it'd take to implement that in the mixerclient.

**Comment by qiwzhang** [comment]
Proxy is extracting as much request attributes as possible.  Mesh attributes should come from Pilot
