### ISSUE TITLE
Idea: if proxy is not compatible with manager or mixer it 503s all outbound traffic

### ISSUE THREAD

**Issue by esnible** [istio/proxy#187]
The debuggability of the system might be improved if the proxy and manager/mixer compared versions and if the  versions did not match the proxy would configure Envoy to return HTTP 502 or 503 with body such as "Istio proxy version 0.123 not compatible with Istio mixer version 0.132".

Currently version mismatches between the proxy and other components look like connectivity or HTTP problems to the caller.

**Comment by qiwzhang** [comment]
gRPC and protobuf are very good at compatibility by design.  That is why a client doesn't need to ask the server version, all versions should work.  It is not a good idea to introduce version checking in order to work around some bugs. (The current in-compatibility is introduced by a bug, ideally, it should be reversed).

**Comment by kyessenov** [comment]
Manager and proxy are packaged together and guaranteed to work. `istioctl` and manager should utilize versioning. Proxy and mixer are GRPC client/server so as long as mixer stays backwards compatible we're good. I do think we need some tag/label to identify which mixer works with which proxy now that we broke compatibility.
