### ISSUE TITLE
Migrate dynamic metadata to SharedFilterState

### ISSUE THREAD

**Issue by yangminzhu** [istio/proxy#1992]
[FilterState](https://github.com/envoyproxy/envoy/issues/4528) is added to as a generic attribute bag shared by all filters.

We will need to move to use it if:
- Dynamic metadata gets deprecated
- AuthN TCP filter is implemented

**Comment by rshriram** [comment]
We need to move to it in general, as its a more flexible and scalable model. It allows third party filters to add metadata that RBAC filter can use.. The current model is pulling from well known filters, limiting the usability of Istio RBAC to istio filters only.

**Comment by diemtvu** [comment]
If some data is used by both, say RBAC and mixer filter, do we have to output to both places?

**Comment by rshriram** [comment]
No.. Just output to a single key (envoy.connection.attributes).. Have both filters use this named state.

**Comment by rshriram** [comment]
Actually hold off on this please. Looking at the bevy of data sharing options in Enovy, the dynamic metadata seems like a better fit. We simply need other filters to write to RBAC filter's dynamic metadata instead of RBAC pulling from everywhere. The struct conversion is a pain but we can make do with this for the moment.

**Comment by yangminzhu** [comment]
Closing this one as we don't need to migrate in the near future, could reopen if needed.
