### ISSUE TITLE
Update istio authn filter to align with changes in Envoy

### ISSUE THREAD

**Issue by yangminzhu** [istio/proxy#2177]
https://github.com/envoyproxy/envoy/pull/6144 Did some large refactor to the SSL struct in Envoy which will break the Isio authentication filter.

- the `Ssl::Connection` is renamed to `Ssl::ConnectionInfo`
- the `uriSanPeerCertificate()` is changed to return `std::vector<std::string>` from `std::string`

/cc @snowp @lizan A quick question, there is a `TODO(snowp): Remove this in favor of StreamInfo::downstreamSslConnection.` in the original envoy PR, I'm wondering is this going to happen soon? I would prefer to resolve the conflicts in one PR in Istio side.

**Comment by lizan** [comment]
So instead of accessing `callbacks_->connection()->ssl()` like here (via FilterContext in istio authn filter though):
https://github.com/istio/proxy/blob/1.1.3/src/envoy/http/authn/authenticator_base.cc#L59

Use `callbacks_->streamInfo()->downstreamSslConnection()` to get the peer information. Rename and return type change should be straightforward.

**Comment by yangminzhu** [comment]
@lizan  Thanks for the comment, it turns out there are some other break changes, sent out a PR to resolve them all.
